site_name: NSI Blaise Pascal
site_url: https://nsi.nastioucha.fr/
site_author: Anaël BARODINE


docs_dir: docs
use_directory_urls: true

# Configuration
theme:
  favicon: icons/key.svg
  logo: icons/key.svg
  name: material

  font:
    text: PT Sans
    code: Roboto Mono
  language: fr
  palette:
    - media : "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Thème nuit
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Thème jour
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.annotate

markdown_extensions:
  # -- Possibilité de nesting arbitraire des blocs de tous types --
  - pymdownx.superfences

  # -- Coloration syntaxique --
  - pymdownx.highlight
  - pymdownx.details      #   qui peuvent se plier/déplier.
  - pymdownx.inlinehilite # coloration inline : `#!python  <python en ligne>`

  # -- Latex --
  # inline : $...$
  # Bloc : $$...$$
  - pymdownx.arithmatex
  - pymdownx.arithmatex:
      generic: true

  # -- Précisions en passant la souris --
  # En bas de document : *[HTML]: Hyper Text Markup Language
  - abbr

  # -- Blocs de texte colorés --
  # Bloc visible : !!! info
  # Bloc déroulant : ??? danger
  # Blocs possibles : note abstract info tip success question warning failure danger bug example quote
  - admonition

  #  -- Notes de bas de page --
  # Dans le corps : Truc[^1]
  # En bas de document : [^1]: ma note.
  - footnotes

  # -- Autres notations --
  - pymdownx.caret # ^^souligné^^ / ^exposant^
  - pymdownx.mark # ==surligné==
  - pymdownx.tilde # ~~barré~~ / ~indice~

  # -- Touches du clavier --
  # inline : ++ctrl+d++
  # https://facelessuser.github.io/pymdown-extensions/extensions/keys/#extendingmodifying-key-map-index
  - pymdownx.keys:
      separator: "\uff0b"
  
  # -- Inclusion de fichiers externes --
  # La notation est : --8<-- "nom-du-fichier"
  # ``` title=".browserslistrc"
  # --8<-- ".browserslistrc"
  # ```
  - pymdownx.snippets

  # -- Volets glissants --
  # === "Volet"
  #   blabla
  # === "Volet 2"
  #   blabla
  - pymdownx.tabbed:
      alternate_style: true

  # -- Cases cochables --
  # Syntaxe : - [ ] / - [x]
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

  # -- Parsing en Markdown du contenus de blocs HTML --
  - md_in_html
  
  # -- Table des matières --
  - toc:
      permalink: ⚓︎
      toc_depth: 3


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # Requis pour afficher le latex côté client

plugins:
  # -- Barre de recherche --
  - search

  # -- Exécution de Python --
  # Syntaxe (bloc de code) : ```python exec="true" html="true"
  # https://pawamoy.github.io/markdown-exec/usage/
  - markdown-exec

  - awesome-nav:
      filename: .nav.yml

